### ISSUE TITLE
Consider dropping a layer on the Keyboardio Atreus, to enable LayerNames

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis-Firmware-Bundle#18]
The Keyboardio Atreus ships with 10 layers enabled, which take up a lot of EEPROM space (almost half of what's available), and that prevents us to introduce pretty much anything that'd use EEPROM, such as the LayerNames plugin.

If we free'd up a layer, we'd have 96 more bytes immediately, 63 of which we could easily use for LayerNames (for 6 chars / layername on average), and still have some to spare.

This would break backwards compatibility, but perhaps we could do that for a good cause.

**Comment by obra** [comment]
let's free up a layer
