### ISSUE TITLE
Consider enabling the DefaultLEDModeConfig plugin for the Model100

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis-Firmware-Bundle#19]
The Model100 firmware ships with a *lot* of LED effects. It would be nice if it was possible to choose the default one, rather than having the keyboard start up with the first one every time it boots, and having to cycle to the one we want.

The `DefaultLEDModeConfig` plugin makes this possible, so I think it should be enabled in the default Model100 firmware.

**Comment by obra** [comment]
I'm fine with that.
