### ISSUE TITLE
Model01 experimental firmware should have IdleLEDs included-- enhancement request

### ISSUE THREAD

**Issue by tmarzolf** [keyboardio/Chrysalis-Firmware-Bundle#8]
In the spirit of making Model01 (and Model100???) commonly requested/usefull features more accessable to Chrysalis only users,  I'd love to see IdleLEDs included in the experimental firmware.

**Comment by algernon** [comment]
This is now completed on master: the Model100 firmware has IdleLEDs available. The Model01 does not, because there isn't enough space.
